
// 用户访问权限
export const USER_ACCESS_LEVEL_NONE = 1;
export const USER_ACCESS_LEVEL_READ = 2;
export const USER_ACCESS_LEVEL_WRITE = 4;
export const USER_ACCESS_LEVEL = {
	USER_ACCESS_LEVEL_NONE,
	USER_ACCESS_LEVEL_READ,
	USER_ACCESS_LEVEL_WRITE,
}
