
// 用户访问权限
export const USER_ACCESS_LEVEL_NONE = 1;
export const USER_ACCESS_LEVEL_READ = 2;
export const USER_ACCESS_LEVEL_WRITE = 4;
export const USER_ACCESS_LEVEL = {
	USER_ACCESS_LEVEL_NONE,
	USER_ACCESS_LEVEL_READ,
	USER_ACCESS_LEVEL_WRITE,
}


export const QINIU_AUDIT_STATE_NO_AUDIT = 0;  // 未审核
export const QINIU_AUDIT_STATE_PASS = 1;      // 审核通过
export const QINIU_AUDIT_STATE_NOPASS = 2;    // 审核未通过
export const QINIU_AUDIT_STATE_FAILED = 3;    // 审核失败

export const QINIU_AUDIT_STATE = {
	QINIU_AUDIT_STATE_NO_AUDIT,
	QINIU_AUDIT_STATE_PASS,
	QINIU_AUDIT_STATE_NOPASS,
	QINIU_AUDIT_STATE_FAILED,
}
