
// 用户访问权限
export const USER_ACCESS_LEVEL_NONE = 0;
export const USER_ACCESS_LEVEL_READ = 30;
export const USER_ACCESS_LEVEL_WRITE = 40;
export const USER_ACCESS_LEVEL = {
	USER_ACCESS_LEVEL_NONE,
	USER_ACCESS_LEVEL_READ,
	USER_ACCESS_LEVEL_WRITE,
}

// 文件审核状态
export const QINIU_AUDIT_STATE_NO_AUDIT = 0;  // 未审核
export const QINIU_AUDIT_STATE_PASS = 1;      // 审核通过
export const QINIU_AUDIT_STATE_NOPASS = 2;    // 审核未通过
export const QINIU_AUDIT_STATE_FAILED = 3;    // 审核失败
export const QINIU_AUDIT_STATE = {
	QINIU_AUDIT_STATE_NO_AUDIT,
	QINIU_AUDIT_STATE_PASS,
	QINIU_AUDIT_STATE_NOPASS,
	QINIU_AUDIT_STATE_FAILED,
}

// 实体类型
export const ENTITY_TYPE_USER = 0; // 用户类型
export const ENTITY_TYPE_SITE = 1; // 站点类型
export const ENTITY_TYPE_PAGE = 2; // 页面类型
export const ENTITY_TYPE = {
	ENTITY_TYPE_USER,
	ENTITY_TYPE_SITE,
	ENTITY_TYPE_PAGE,
}

// 站点可见性
export const ENTITY_VISIBILITY_PUBLIC = 0; // 公开
export const ENTITY_VISIBILITY_PRIVATE = 1; // 私有
export const ENTITY_VISIBILITY = {
	ENTITY_VISIBILITY_PUBLIC,
	ENTITY_VISIBILITY_PRIVATE,
}

// OAUTH_SERVICE_TYPE
export const OAUTH_SERVICE_TYPE_QQ = 0;
export const OAUTH_SERVICE_TYPE_WEIXIN = 1;
export const OAUTH_SERVICE_TYPE_GITHUB = 2;
export const OAUTH_SERVICE_TYPE_XINLANG =3;
export const OAUTH_SERVICE_TYPE = {
	OAUTH_SERVICE_TYPE_QQ,
	OAUTH_SERVICE_TYPE_WEIXIN,
	OAUTH_SERVICE_TYPE_GITHUB,
	OAUTH_SERVICE_TYPE_XINLANG,
}


export default {
	USER_ACCESS_LEVEL,
	QINIU_AUDIT_STATE,
	ENTITY_TYPE,
	ENTITY_VISIBILITY,
}
